auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Muksame's blog
url: http://mukosame.github.io
feed: /atom.xml
author_info: <a href="http://mukosame.github.io/">Mukosame</a>
